#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InvataChimie.Resource", IsApplication=true)]

namespace InvataChimie
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int capTitle = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Flag_of_Romania = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Flag_of_United_Kingdom = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_language_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int round_button = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int CapImage = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CapName = 2131230723;
			
			// aapt resource value: 0x7f08000b
			public const int MyButton = 2131230731;
			
			// aapt resource value: 0x7f080007
			public const int english = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int english_layout = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int invata = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int joaca = 2131230730;
			
			// aapt resource value: 0x7f080008
			public const int listView = 2131230728;
			
			// aapt resource value: 0x7f08000d
			public const int menu_language = 2131230733;
			
			// aapt resource value: 0x7f080005
			public const int romanian = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int romanian_layout = 2131230724;
			
			// aapt resource value: 0x7f08000c
			public const int startButton = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int toolbar = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int webView = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int cap_details_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int cap_row = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int language_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int learn_layout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int learn_or_play_layout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int start_layout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int toolbar = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int top_menus = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int cap0 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cap1 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int cap2 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int cap3 = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int MyTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int button_text = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
